version: "2"
services:
  nginx:
    image: ongr/nginx
    links:
      - fpm
    ports:
      - "$LOCAL_NGINX_PORT:80"
    volumes:
      - ".docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www"
    networks:
      - frontend
  fpm:
    build:
      context: .docker/build/fpm
      args:
        LOCAL_USER_ID: $LOCAL_USER_ID
        LOCAL_GROUP_ID: $LOCAL_GROUP_ID
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    links:
      - mariadb
    volumes:
      - ".docker/.composer:/.composer"
      - "./:/var/www"
      - "$LOCAL_SSH_PRIVATE_KEY:/home/user/.ssh/id_rsa:ro"
    networks:
      - frontend
      - backend
    environment:
      XDEBUG_CONFIG: remote_host=$LOCAL_XDEBUG_HOST
  npm:
    image: ongr/nodejs:6.4.0
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    volumes:
      - ".docker/.npm:/home/.npm"
      - "./:/home/app"
      - "/usr/local/lib/node_modules"
    networks:
      - frontend
  mariadb-data:
    image: tianon/true
    volumes:
      - /var/lib/mysql
    networks:
      - backend
  mariadb:
    image: mariadb:10.1.10
    ports:
      - "$LOCAL_MYSQL_PORT:3306"
    volumes_from:
      - "mariadb-data"
    environment:
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
networks:
  frontend:
    driver: bridge
    ipam:
      config:
      - subnet: $LOCAL_FRONTEND_SUBNET
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: $LOCAL_BACKEND_SUBNET
