<?php

namespace AppBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByColumns(Array $columns){
        array_walk($columns, function(&$key) { $key = "brand.".$key; });

        return $this->createQueryBuilder('brand')
            ->select($columns)
            ->getQuery()
            ->execute();
    }

}
