<?php

namespace AppBundle\Repository;

/**
 * DoorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoorRepository extends \Doctrine\ORM\EntityRepository
{
}
