<?php

namespace AppBundle\Repository;

/**
 * FuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelRepository extends \Doctrine\ORM\EntityRepository
{
}
