<?php

namespace AppBundle\Repository;

/**
 * GearboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GearboxRepository extends \Doctrine\ORM\EntityRepository
{
}
