<?php

namespace AppBundle\Repository;

/**
 * HandlebarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlebarRepository extends \Doctrine\ORM\EntityRepository
{
}
