<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * WatchlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchlistRepository extends EntityRepository
{
    /**
     *
     * @param User $user
     * @return mixed
     */
    public function findByUser(User $user)
    {
        $conn = $this->getEntityManager()
            ->getConnection();

        $sql = '
                SELECT *
                FROM watchlist wl
                JOIN user usr ON wl.user_id = usr.id
                JOIN auto a ON a.watchlist_id = wl.id
                WHERE wl.user_id = :user';
        $stmt = $conn->prepare($sql);
        $stmt->execute(array('user' => $user->getId()));
        return $stmt->fetchAll();
    }
}
