<?php

namespace AppBundle\Repository;

/**
 * WheelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WheelRepository extends \Doctrine\ORM\EntityRepository
{
}
